# Generated by Django 5.2.17 on 2026-08-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_created_date_created_time'),
        ('leads', '0003_backfill_created_by_email'),
    ]

    operations = [
    ]
