# Generated by Django 5.2.17 on 2026-08-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_deleteddatarecovery'),
        ('leads', '0004_merge_20260810_1749'),
    ]

    operations = [
    ]
